[HEADER]
VERSION=2

[BASIC]
WHEELBASE=2.625
CG_LOCATION=0.42

[ARB]
FRONT=28000
REAR=7500

; Original Drift Setup
[FRONT]
TYPE=STRUT
BASEY=-0.13
TRACK=1.64
ROD_LENGTH=0.060	
HUB_MASS=49	
RIM_OFFSET=0.0
STRUT_CAR=0.17, 0.41, -0.036141
STRUT_TYRE=0.055, -0.145, 0.032
WBCAR_BOTTOM_FRONT=0.470, -0.13, 0.004		
WBCAR_BOTTOM_REAR=0.470, -0.13, -0.33		
WBTYRE_BOTTOM=0.055, -0.145, 0.032			    
WBCAR_STEER=0.47, -0.13, 0.1			    
WBTYRE_STEER=0.0485, -0.145, 0.1
TOE_OUT=0.0000
STATIC_CAMBER=-5.5
SPRING_RATE=61000
PROGRESSIVE_SPRING_RATE=0
BUMP_STOP_RATE=50000
BUMPSTOP_UP=0.13
BUMPSTOP_DN=0.06
PACKER_RANGE=0.13
DAMP_BUMP=3000
DAMP_FAST_BUMP=1600
DAMP_FAST_BUMPTHRESHOLD=0.10
DAMP_REBOUND=8900
DAMP_FAST_REBOUND=4700
DAMP_FAST_REBOUNDTHRESHOLD=0.10


; Original Drift Setup
[REAR]
TYPE=DWB
BASEY=-0.16
TRACK=1.6
ROD_LENGTH=0.0190						
HUB_MASS=60	
WBCAR_TOP_FRONT=0.315, 0.055, 0.24
WBCAR_TOP_REAR=0.41, 0.085, -0.00
WBCAR_BOTTOM_FRONT=0.24, -0.155, 0.27
WBCAR_BOTTOM_REAR=0.43, -0.125, -0.005
WBTYRE_TOP=0.12, 0.095, -0.00
WBTYRE_BOTTOM=0.1, -0.16, 0.02
WBCAR_STEER=0.575, -0.025, -0.12
WBTYRE_STEER=0.17, -0.0200, -0.16
TOE_OUT=0.0005
STATIC_CAMBER=0.0
SPRING_RATE=50000
PROGRESSIVE_SPRING_RATE=0.95
BUMP_STOP_RATE=92500
BUMPSTOP_UP=0.06						
BUMPSTOP_DN=0.01
PACKER_RANGE=0.15						
DAMP_BUMP=5000	
DAMP_FAST_BUMP=1000	
DAMP_FAST_BUMPTHRESHOLD=0.06					
DAMP_REBOUND=5500					
DAMP_FAST_REBOUND=3500
DAMP_FAST_REBOUNDTHRESHOLD=0.08

[GRAPHICS_OFFSETS]
WHEEL_LF=-0.025
SUSP_LF=-0.02
WHEEL_RF=0.025
SUSP_RF=0.02
WHEEL_LR=-0.05
SUSP_LR=-0.05
WHEEL_RR=0.05
SUSP_RR=0.05


